### ISSUE TITLE
[Gotify] Support specifying of priority

### ISSUE THREAD

**Issue by krohrsb** [ix-ai/alertmanager-notifier#7]
Gotify has a notion of message priority which is used in various ways. It would be great if this notifier tool could perhaps interpret an annotation for priority. Kind of like this project https://gitlab.com/A1kmm/alertmanager-to-gotify

Your projects template capability is great. Just need priority to make it complete!

**Comment by tlex** [comment]
Thanks for the request. I've released [v0.2.0](https://github.com/ix-ai/alertmanager-notifier/releases/tag/v0.2.0) with support for priority for gotify messages.

**Comment by krohrsb** [comment]
Awesome! Very much appreciated.
