### ISSUE TITLE
EXCLUDE_LABELS env is broken

### ISSUE THREAD

**Issue by ahmadalli** [ix-ai/alertmanager-notifier#9]
I've tried setting `EXCLUDE_LABELS` to `yes` and `no`. Labels won't be included on the alert either way

**Comment by ahmadalli** [comment]
I've checked the logs and it's always logging 

> EXCLUDE_LABELS is set to `True`

**Comment by ahmadalli** [comment]
I think maybe this causes the problem?
https://github.com/ix-ai/alertmanager-notifier/blob/06311def4a1fa025e99274eb05ccd6be1213d86a/alertmanager-notifier/lib/notifiers.py#L25

**Comment by tlex** [comment]
That one is a leftover - I see I used to set defaults all over the place. I'll get rid of that :smiley: 

Edit: commit 1bc1d3f3fe48c73a53c4e76ca99cd180790d9ae3

**Comment by tlex** [comment]
Thanks for letting me know about this issue. It should be fixed now in master.
